apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-application-manager
  namespace: argocd
spec:
  generators:
    generators:
    - git:
        repoURL: https://github.com/dsfwoo8172/argocd-pratice.git
        revision: main
        files:
          - path: charts/**/config.json
  template:
    metadata:
      name: '{{env}}-hello-world'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      sources:
        - repoURL: https://github.com/dsfwoo8172/argocd-pratice.git
          targetRevision: main
          path: charts/hello-world
          helm:
            valueFiles:
              - values.yaml
              - '{{valuesFile}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
