apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-application-manager
  namespace: argocd
spec:
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/
  goTemplate: true # enable to use golang syntax in the application set
  goTemplateOptions: ["missingkey=error"] # error if the key is missing
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/dsfwoo8172/argocd-pratice.git
              revision: main
              files:
                - path: charts/**/config.json
          - list:
              # Refer to environment variables in the config.json
              elements:
                - env: prod
                - env: test
  template:
    metadata:
      name: '{{.path.basename}}-{{.env}}' # path.basename is the name of Sub-Folder
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{.project}}'
      destination:
        # server: '{{index .environments .env "server"}}'
        name: '{{index .environments .env "clusterName"}}'
        namespace: '{{.namespace}}'
      sources:
        - repoURL: '{{.source.repoURL}}'
          targetRevision: '{{.source.targetRevision}}'
          path: '{{.source.path}}'
          helm:
            valueFiles:
              - values.yaml
              - '{{index .environments .env "valuesFile"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
