apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-application-manager
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/dsfwoo8172/argocd-pratice.git
              revision: main
              files:
                - path: charts/**/config.json
          - list:
              elements:
                - env: prod
                - env: test
  template:
    metadata:
      name: '{{appName}}-{{.env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{project}}'
      destination:
        server: '{{environments.{{.env}}.server}}'
        namespace: '{{environments.{{.env}}.namespace}}'
      sources:
        - repoURL: '{{source.repoURL}}'
          targetRevision: '{{source.targetRevision}}'
          path: '{{source.path}}'
          helm:
            valueFiles:
              - values.yaml
              - '{{environments.{{.env}}.valuesFile}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
