apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-manager
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/dsfwoo8172/argocd-pratice.git
      revision: main
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/dsfwoo8172/argocd-pratice.git
        targetRevision: main
        path: 'apps/{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'