apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-manager
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/dsfwoo8172/argocd-pratice.git
      revision: main
      files:
        - path: apps/**/config.json
  template:
    metadata:
      name: '{{destination.namespace}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{project}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: '{{source.repoURL}}'
        targetRevision: '{{source.targetRevision}}'
        path: '{{source.path}}'
      destination:
        server: '{{destination.server}}'
        namespace: '{{destination.namespace}}'