apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-manager
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/dsfwoo8172/argocd-pratice.git
      revision: main
      files:
        - path: charts/**/config.json
  template:
    metadata:
      name: '{{appName}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{project}}'
      destination:
        server: '{{destination.server}}'
        namespace: '{{destination.namespace}}'
      sources:
        - repoURL: '{{source.repoURL}}'
          targetRevision: '{{source.targetRevision}}'
          path: '{{source.path}}'
          helm:
            valueFiles:
              - values.yaml
              - '{{valuesFile}}' # 後面的 values 會蓋過前面的
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
